name: Learn Github action

on: [push]


jobs:
  
  First_job:
    name: First job in action 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run:  | 
          npm install -g bats
          bats -v

  Second_job:
    name: Second job in action
    runs-on: macos-11.0
    steps: 
     - uses: actions/setup-node@v1
     - run: |
        node -v 
        uname -a 